max_cpus: 4  # max CPUs for any single job

genomes:
  SARS-CoV-2:
    fasta: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz

genome_trim3_polyA: true  # do we trim A nucleotides from 3' end of genome?

aligners:
  - bbmap
  - bwa-mem2

scratch_dir: results/_scratch/  # put scratch files here

accessions:
  SRR10971381:
    study_url: https://www.nature.com/articles/s41586-020-2008-3
    sample_description: WH-Human 1 (Wu et al)
  SRR11092056:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV06 (Zhou et al)
  SRR11092057:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV04 (Zhou et al)
  SRR11092058:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV02 (Zhou et al)
  SRR11092059:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV07-02 (Zhou et al)
  SRR11092060:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV06-02 (Zhou et al)    
  SRR11092061:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV05 (Zhou et al)
  SRR11092062:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV04-02 (Zhou et al)
  SRR11092063:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV02-02 (Zhou et al)
  SRR11092064:
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    sample_description: WIV07 (Zhou et al)
  SRR10903401:
    study_url: https://www.tandfonline.com/doi/full/10.1080/22221751.2020.1725399
    sample_description: WHU02 (Chen et al)
  SRR10903402:
    study_url: https://www.tandfonline.com/doi/full/10.1080/22221751.2020.1725399
    sample_description: WHU01 (Chen et al) 
  SRR11177792:
    study_url: https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30067-0/fulltext
    sample_description: Nepal student (Bastola et al)
