# -----------------------------------------------------------------
# General options related to pipeline setup
# -----------------------------------------------------------------
max_cpus: 4  # max CPUs for any single job

# Put scratch files here, because pipeline makes and then deletes many files
scratch_dir: /fh/scratch/delete90/bloom_j/user/jbloom/deleted_pangolin_CoV/scratch

# Include per-sample pileup charts in report? Bloats report size.
per_sample_pileups_in_report: false

# -----------------------------------------------------------------
# Viral reference genomes
# -----------------------------------------------------------------
# align against these genomes
genomes:
  Wuhan-Hu-1:
    fasta: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz
    name: NC_045512.2

genome_trim3_polyA: true  # do we trim A nucleotides from 3' end of viral genomes?

# when mismatches, are they also present in these close-ish viral relatives?
comparator_genomes:
  RaTG13:
    genbank: MN996532.2
  GD_Pangolin_MP789:
    genbank: MT121216.1
  RacCS203:
    genbank: MW251308.1

# -----------------------------------------------------------------
# Host genomes used for calling sex of patient
# -----------------------------------------------------------------
host_genomes:
  human:
    fasta: ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
    sex_chromosomes:
      male: Y
      female: X

# -----------------------------------------------------------------
# Options related to how to do SRA downloads
# -----------------------------------------------------------------
# We download the *.sra from the Google API link:
google_api_base: https://storage.googleapis.com/nih-sequence-read-archive/run

# -----------------------------------------------------------------
# General alignment and consensus calling options
# -----------------------------------------------------------------
# short-read aligners to use
aligners:
  - bbmap
  - bwa-mem2

# in pileups, only consider sites where Q score >= this; also used for `fastp` preprocessing
minq: 20
# in `fastp` pre-processing require at least this read length
min_read_length: 20

# Criteria used to call consensus from pileup, and then determine
# if different from reference or Genbank.
consensus_min_coverage: 4  # require >= this coverage
consensus_min_frac: 0.75  # require most common base > this fraction

# report fraction viral genome covered at >= following depths
report_frac_coverage: [1, 2, 4, 10, 20, 50, 100]

# -----------------------------------------------------------------
# Samples on SRA to analyze.
# -----------------------------------------------------------------
samples:
  # -----------------------------------------------------------------
  # From Wu et al paper reporting Wuhan-Hu-1
  # -----------------------------------------------------------------
  Wuhan-Hu-1_Wu_et_al:
    accessions: [SRR10971381]
    study_url: https://www.nature.com/articles/s41586-020-2008-3
    genbank: MN908947
    sex: male
    collection_date: 2020-01-02
  # -----------------------------------------------------------------
  # From Wuhan Institute of Virology Zhou et al paper
  # -----------------------------------------------------------------
  WIV02_Zhou_et_al:
    accessions: [SRR11092058, SRR11092063]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996527
    sex: male
    collection_date: 2019-12-30
  WIV02-01_Zhou_et_al:
    accessions: [SRR11092058]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996527
    sex: male
    collection_date: 2019-12-30
  WIV02-02_Zhou_et_al:
    accessions: [SRR11092063]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996527
    sex: male
    collection_date: 2019-12-30
  WIV04_Zhou_et_al:
    accessions: [SRR11092057, SRR11092062]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996528
    sex: female
    collection_date: 2019-12-30
  WIV04-01_Zhou_et_al:
    accessions: [SRR11092057]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996528
    sex: female
    collection_date: 2019-12-30
  WIV04-02_Zhou_et_al:
    accessions: [SRR11092062]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996528
    sex: female
    collection_date: 2019-12-30
  WIV05_Zhou_et_al:
    accessions: [SRR11092061]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996529
    sex: female
    collection_date: 2019-12-30
  WIV06_Zhou_et_al:
    accessions: [SRR11092056, SRR11092060]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996530
    sex: male
    collection_date: 2019-12-30
  WIV06-01_Zhou_et_al:
    accessions: [SRR11092056]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996530
    sex: male
    collection_date: 2019-12-30
  WIV06-02_Zhou_et_al:
    accessions: [SRR11092060]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996530
    sex: male
    collection_date: 2019-12-30
  WIV07_Zhou_et_al:
    accessions: [SRR11092064, SRR11092059]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996531
    sex: male
    collection_date: 2019-12-30
  WIV07-01_Zhou_et_al:
    accessions: [SRR11092064]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996531
    sex: male
    collection_date: 2019-12-30
  WIV07-02_Zhou_et_al:
    accessions: [SRR11092059]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996531
    sex: male
    collection_date: 2019-12-30
  # -----------------------------------------------------------------
  # From Wuhan University Chen et al paper
  # -----------------------------------------------------------------
  WHU01_Chen_et_al:
    accessions: [SRR10903402]
    study_url: https://www.tandfonline.com/doi/full/10.1080/22221751.2020.1725399
    genbank: MN988668
    sex: male
    collection_date: 2020-01-02
  WHU02_Chen_et_al:
    accessions: [SRR10903401]
    study_url: https://www.tandfonline.com/doi/full/10.1080/22221751.2020.1725399
    genbank: MN988669
    sex: female
    collection_date: 2020-01-02
  # -----------------------------------------------------------------
  # From first case in Nepal
  # -----------------------------------------------------------------
  Nepal-student_Bastola_et_al:
    accessions: [SRR11177792]
    study_url: https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30067-0/fulltext
    genbank: MT072688
    sex: male
    collection_date: 2020-01-13
  # -----------------------------------------------------------------
  # From this BioProject:
  # https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA616446
  # -----------------------------------------------------------------
  HBCDC-HB-01_2019:
    accessions: [SRR11454614]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479128
    collection_date: 2019-12-30
  HBCDC-HB-02_2019:
    accessions: [SRR11454615]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479127
    collection_date: 2019-12-30
  HBCDC-HB-03_2019:
    accessions: [SRR11454613]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479129
    collection_date: 2019-12-30
  HBCDC-HB-04_2019:
    accessions: [SRR11454612]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479130
    collection_date: 2019-12-30
  HBCDC-HB-01_2020:
    accessions: [SRR11454608]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479134
    collection_date: 2020-01-08
  HBCDC-HB-02_2020:
    accessions: [SRR11454609]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479133
    collection_date: 2020-01-17
  HBCDC-HB-03_2020:
    accessions: [SRR11454610]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479132
    collection_date: 2020-01-18
  HBCDC-HB-04_2020:
    accessions: [SRR11454611]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479131
    collection_date: 2020-01-18
  HBCDC-HB-06_2020:
    accessions: [SRR11454607]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479135
    collection_date: 2020-02-07
  HBCDC-HB-07_2020:
    accessions: [SRR11454606]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/14479136
    collection_date: 2020-02-08
  # -----------------------------------------------------------------
  # From this BioProject (detecting SARS-CoV02 in fecal swabs)
  # https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA611496
  # -----------------------------------------------------------------
  fecal_swab_BGI:
    accessions: [SRR11267811]
    study_url: https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN14332760
    collection_date: 2020-02-22
  # -----------------------------------------------------------------
  # Samples from this BioProject:
  # https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA605907
  # which corresponds to this paper:
  # https://pubmed.ncbi.nlm.nih.gov/32129843/
  # -----------------------------------------------------------------
  WH19001_Shen_et_al:
    accessions: [SRR11059947]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2019-12-30
    sex: female
  WH19002_Shen_et_al:
    accessions: [SRR11059946]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2019-12-30
    sex: female
  WH19003_Shen_et_al:
    accessions: [SRR11059945]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2019-12-30
    sex: male
  WH19004_Shen_et_al:
    accessions: [SRR11059944]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2020-01-01
    sex: male
  WH19010_Shen_et_al:
    accessions: [SRR11059943]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2019-12-30
    sex: male
  WH19012_Shen_et_al:
    accessions: [SRR11059942]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2019-12-30
    sex: male
  WH19016_Shen_et_al:
    accessions: [SRR11059941]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2020-01-01
    sex: female
  WH19053_Shen_et_al:
    accessions: [SRR11059940]
    study_url: https://pubmed.ncbi.nlm.nih.gov/32129843/
    collection_date: 2019-12-30
    sex: male
  # -----------------------------------------------------------------
  # Beijing Genome Institute samples from this BioProject
  # https://www.ncbi.nlm.nih.gov/bioproject/PRJEB36487
  # do not have raw data: these are WH1, WH2, WH3, and WH4.
  # -----------------------------------------------------------------

  # -----------------------------------------------------------------
  # I have not yet found raw data for the Lu et al Lancet paper
  # https://www.thelancet.com/article/S0140-6736(20)30251-8/fulltext
  # -----------------------------------------------------------------
