max_cpus: 4  # max CPUs for any single job

scratch_dir: results/_scratch/  # put scratch files here

# genome against which we align data
genomes:
  Wuhan-Hu-1_NC_045512.2:
    fasta: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz
    name: NC_045512.2

genome_trim3_polyA: true  # do we trim A nucleotides from 3' end of genome?

# short-read aligners to use
aligners:
  - bbmap
  - bwa-mem2

minq: 20  # in pileups, only consider sites where Q score >= this

# Criteria used to call consensus from pileup, and then determine
# if different from reference or Genbank.
consensus_min_coverage: 2  # require >= this coverage
consensus_min_frac: 0.5  # require most common base > this fraction

# information on samples to analyze
samples:
  Wuhan-Hu-1_Wu_et_al:
    accessions: [SRR10971381]
    study_url: https://www.nature.com/articles/s41586-020-2008-3
    genbank: MN908947
    sex: male
  WIV02_Zhou_et_al:
    accessions: [SRR11092058, SRR11092063]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996527
    sex: male
  WIV02-01_Zhou_et_al:
    accessions: [SRR11092058]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996527
    sex: male
  WIV02-02_Zhou_et_al:
    accessions: [SRR11092063]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996527
    sex: male
  WIV04_Zhou_et_al:
    accessions: [SRR11092057, SRR11092062]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996528
    sex: female
  WIV04-01_Zhou_et_al:
    accessions: [SRR11092057]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996528
    sex: female
  WIV04-02_Zhou_et_al:
    accessions: [SRR11092062]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996528
    sex: female
  WIV05_Zhou_et_al:
    accessions: [SRR11092061]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996529
    sex: female
  WIV06_Zhou_et_al:
    accessions: [SRR11092056, SRR11092060]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996530
    sex: male
  WIV06-01_Zhou_et_al:
    accessions: [SRR11092056]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996530
    sex: male
  WIV06-02_Zhou_et_al:
    accessions: [SRR11092060]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996530
    sex: male
  WIV07_Zhou_et_al:
    accessions: [SRR11092064, SRR11092059]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996531
    sex: male
  WIV07-01_Zhou_et_al:
    accessions: [SRR11092064]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996531
    sex: male
  WIV07-02_Zhou_et_al:
    accessions: [SRR11092059]
    study_url: https://www.nature.com/articles/s41586-020-2012-7
    genbank: MN996531
    sex: male
  WHU01_Chen_et_al:
    accessions: [SRR10903402]
    study_url: https://www.tandfonline.com/doi/full/10.1080/22221751.2020.1725399
    genbank: MN988668
    sex: male
  WHU02_Chen_et_al:
    accessions: [SRR10903401]
    study_url: https://www.tandfonline.com/doi/full/10.1080/22221751.2020.1725399
    genbank: MN988669
    sex: female
  Nepal-student_Bastola_et_al:
    accessions: [SRR11177792]
    study_url: https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30067-0/fulltext
    genbank: MT072688
    sex: male
