  # -----------------------------------------------------------------
  # BioProject PRJNA612766
  # -----------------------------------------------------------------
  A1_PRJNA612766:
    accessions: ['SRR11313282', 'SRR11313334']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  A2_PRJNA612766:
    accessions: ['SRR11313271', 'SRR11313461']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  A4_PRJNA612766:
    accessions: ['SRR11313417', 'SRR11313428']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  A6_PRJNA612766:
    accessions: ['SRR11313479', 'SRR11313490']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  A9_PRJNA612766:
    accessions: ['SRR11313345', 'SRR11313356']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  A11_PRJNA612766:
    accessions: ['SRR11313455', 'SRR11313456']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  A12_PRJNA612766:
    accessions: ['SRR11313473', 'SRR11313474']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  B1_PRJNA612766:
    accessions: ['SRR11313453', 'SRR11313454']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  B2_PRJNA612766:
    accessions: ['SRR11313451', 'SRR11313452']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  B3_PRJNA612766:
    accessions: ['SRR11313448', 'SRR11313449']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  B4_PRJNA612766:
    accessions: ['SRR11313322', 'SRR11313333']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  B9_PRJNA612766:
    accessions: ['SRR11313445', 'SRR11313446']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  C1_PRJNA612766:
    accessions: ['SRR11313287', 'SRR11313289']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  C2_PRJNA612766:
    accessions: ['SRR11313285', 'SRR11313286']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  C9_PRJNA612766:
    accessions: ['SRR11313441', 'SRR11313442']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  C11_PRJNA612766:
    accessions: ['SRR11313300', 'SRR11313311']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  C12_PRJNA612766:
    accessions: ['SRR11313443', 'SRR11313444']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  D9_PRJNA612766:
    accessions: ['SRR11313436', 'SRR11313437']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  D11_PRJNA612766:
    accessions: ['SRR11313438', 'SRR11313440']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  D12_PRJNA612766:
    accessions: ['SRR11313280', 'SRR11313281']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  E1_PRJNA612766:
    accessions: ['SRR11313276', 'SRR11313277']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  E3_PRJNA612766:
    accessions: ['SRR11313430', 'SRR11313431']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  E5_PRJNA612766:
    accessions: ['SRR11313274', 'SRR11313275']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  E6_PRJNA612766:
    accessions: ['SRR11313427', 'SRR11313429']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  E11_PRJNA612766:
    accessions: ['SRR11313434', 'SRR11313435']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  E12_PRJNA612766:
    accessions: ['SRR11313432', 'SRR11313433']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  F5_PRJNA612766:
    accessions: ['SRR11313270', 'SRR11313470']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  F8_PRJNA612766:
    accessions: ['SRR11313423', 'SRR11313424']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  F11_PRJNA612766:
    accessions: ['SRR11313425', 'SRR11313426']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  G1_PRJNA612766:
    accessions: ['SRR11313468', 'SRR11313469']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  G11_PRJNA612766:
    accessions: ['SRR11313421', 'SRR11313422']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  G12_PRJNA612766:
    accessions: ['SRR11313419', 'SRR11313420']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  H9_PRJNA612766:
    accessions: ['SRR11313464', 'SRR11313465']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  H12_PRJNA612766:
    accessions: ['SRR11313466', 'SRR11313467']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: early in epidemic
  R01_PRJNA612766:
    accessions: ['SRR11313409', 'SRR11313410']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R02_PRJNA612766:
    accessions: ['SRR11313406', 'SRR11313408']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R03_PRJNA612766:
    accessions: ['SRR11313269', 'SRR11313471']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R04_PRJNA612766:
    accessions: ['SRR11313509']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R05_PRJNA612766:
    accessions: ['SRR11313507', 'SRR11313508']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R06_PRJNA612766:
    accessions: ['SRR11313505', 'SRR11313506']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R07_PRJNA612766:
    accessions: ['SRR11313503', 'SRR11313504']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R08_PRJNA612766:
    accessions: ['SRR11313500', 'SRR11313502']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R09_PRJNA612766:
    accessions: ['SRR11313498', 'SRR11313499']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R10_PRJNA612766:
    accessions: ['SRR11313496', 'SRR11313497']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R11_PRJNA612766:
    accessions: ['SRR11313494', 'SRR11313495']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R12_PRJNA612766:
    accessions: ['SRR11313492', 'SRR11313493']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R13_PRJNA612766:
    accessions: ['SRR11313489', 'SRR11313491']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R14_PRJNA612766:
    accessions: ['SRR11313487', 'SRR11313488']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R15_PRJNA612766:
    accessions: ['SRR11313485', 'SRR11313486']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R16_PRJNA612766:
    accessions: ['SRR11313483', 'SRR11313484']
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020