  # -----------------------------------------------------------------
  # BioProject PRJNA612766
  # -----------------------------------------------------------------
  plasmid-1000cp-replicate01-1h_PRJNA612766:
    accessions: ['SRR11313331']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate01-2h_PRJNA612766:
    accessions: ['SRR11313330']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate01-4h_PRJNA612766:
    accessions: ['SRR11313329']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate01-10min_PRJNA612766:
    accessions: ['SRR11313335']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate01-30min_PRJNA612766:
    accessions: ['SRR11313332']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate02-1h_PRJNA612766:
    accessions: ['SRR11313326']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate02-2h_PRJNA612766:
    accessions: ['SRR11313325']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate02-4h_PRJNA612766:
    accessions: ['SRR11313324']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate02-10min_PRJNA612766:
    accessions: ['SRR11313328']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate02-30min_PRJNA612766:
    accessions: ['SRR11313327']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate03-1h_PRJNA612766:
    accessions: ['SRR11313320']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate03-2h_PRJNA612766:
    accessions: ['SRR11313319']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate03-4h_PRJNA612766:
    accessions: ['SRR11313318']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate03-10min_PRJNA612766:
    accessions: ['SRR11313323']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate03-30min_PRJNA612766:
    accessions: ['SRR11313321']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate04-1h_PRJNA612766:
    accessions: ['SRR11313315']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate04-2h_PRJNA612766:
    accessions: ['SRR11313314']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate04-4h_PRJNA612766:
    accessions: ['SRR11313313']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate04-10min_PRJNA612766:
    accessions: ['SRR11313317']
    collected_by: Aisi Fu
  plasmid-1000cp-replicate04-30min_PRJNA612766:
    accessions: ['SRR11313316']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate01-1h_PRJNA612766:
    accessions: ['SRR11313309']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate01-2h_PRJNA612766:
    accessions: ['SRR11313308']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate01-4h_PRJNA612766:
    accessions: ['SRR11313307']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate01-10min_PRJNA612766:
    accessions: ['SRR11313312']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate01-30min_PRJNA612766:
    accessions: ['SRR11313310']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate02-1h_PRJNA612766:
    accessions: ['SRR11313304']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate02-2h_PRJNA612766:
    accessions: ['SRR11313303']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate02-4h_PRJNA612766:
    accessions: ['SRR11313302']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate02-10min_PRJNA612766:
    accessions: ['SRR11313306']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate02-30min_PRJNA612766:
    accessions: ['SRR11313305']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate03-1h_PRJNA612766:
    accessions: ['SRR11313298']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate03-2h_PRJNA612766:
    accessions: ['SRR11313297']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate03-4h_PRJNA612766:
    accessions: ['SRR11313296']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate03-10min_PRJNA612766:
    accessions: ['SRR11313301']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate03-30min_PRJNA612766:
    accessions: ['SRR11313299']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate04-1h_PRJNA612766:
    accessions: ['SRR11313293']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate04-2h_PRJNA612766:
    accessions: ['SRR11313292']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate04-4h_PRJNA612766:
    accessions: ['SRR11313291']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate04-10min_PRJNA612766:
    accessions: ['SRR11313295']
    collected_by: Aisi Fu
  plasmid-3000cp-replicate04-30min_PRJNA612766:
    accessions: ['SRR11313294']
    collected_by: Aisi Fu