  # -----------------------------------------------------------------
  # BioProject PRJNA612766, host Homo sapiens
  # -----------------------------------------------------------------
  R03-4h_PRJNA612766:
    accessions: [SRR11313269]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  F5-10min_PRJNA612766:
    accessions: [SRR11313270]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A2-10min_PRJNA612766:
    accessions: [SRR11313271]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  F12-4h_PRJNA612766:
    accessions: [SRR11313272]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  F12-10min_PRJNA612766:
    accessions: [SRR11313273]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E5-4h_PRJNA612766:
    accessions: [SRR11313274]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E5-10min_PRJNA612766:
    accessions: [SRR11313275]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E1-4h_PRJNA612766:
    accessions: [SRR11313276]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E1-10min_PRJNA612766:
    accessions: [SRR11313277]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D2-4h_PRJNA612766:
    accessions: [SRR11313278]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D2-10min_PRJNA612766:
    accessions: [SRR11313279]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D12-4h_PRJNA612766:
    accessions: [SRR11313280]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D12-10min_PRJNA612766:
    accessions: [SRR11313281]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A1-4h_PRJNA612766:
    accessions: [SRR11313282]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D10-4h_PRJNA612766:
    accessions: [SRR11313283]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D10-10min_PRJNA612766:
    accessions: [SRR11313284]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C2-4h_PRJNA612766:
    accessions: [SRR11313285]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C2-10min_PRJNA612766:
    accessions: [SRR11313286]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C1-4h_PRJNA612766:
    accessions: [SRR11313287]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  respiratory viruses-2h_PRJNA612766:
    accessions: [SRR11313288]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 15-Jan-2020
  C1-10min_PRJNA612766:
    accessions: [SRR11313289]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  respiratory viruses-10min_PRJNA612766:
    accessions: [SRR11313290]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 15-Jan-2020
  C11-4h_PRJNA612766:
    accessions: [SRR11313300]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C11-10min_PRJNA612766:
    accessions: [SRR11313311]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B4-4h_PRJNA612766:
    accessions: [SRR11313322]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B4-10min_PRJNA612766:
    accessions: [SRR11313333]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A1-10min_PRJNA612766:
    accessions: [SRR11313334]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A9-4h_PRJNA612766:
    accessions: [SRR11313345]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A9-10min_PRJNA612766:
    accessions: [SRR11313356]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A8-4h_PRJNA612766:
    accessions: [SRR11313367]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A8-10min_PRJNA612766:
    accessions: [SRR11313378]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A7-4h_PRJNA612766:
    accessions: [SRR11313389]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A7-10min_PRJNA612766:
    accessions: [SRR11313400]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  R02-4h_PRJNA612766:
    accessions: [SRR11313406]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R02-10min_PRJNA612766:
    accessions: [SRR11313408]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R01-4h_PRJNA612766:
    accessions: [SRR11313409]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R01-10min_PRJNA612766:
    accessions: [SRR11313410]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  PC2-4h_PRJNA612766:
    accessions: [SRR11313411]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  PC2-10min_PRJNA612766:
    accessions: [SRR11313412]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  NC2-4h_PRJNA612766:
    accessions: [SRR11313413]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  H3-4h_PRJNA612766:
    accessions: [SRR11313414]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  H3-10min_PRJNA612766:
    accessions: [SRR11313415]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G6-4h_PRJNA612766:
    accessions: [SRR11313416]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A4-4h_PRJNA612766:
    accessions: [SRR11313417]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G6-10min_PRJNA612766:
    accessions: [SRR11313418]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G12-4h_PRJNA612766:
    accessions: [SRR11313419]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G12-10min_PRJNA612766:
    accessions: [SRR11313420]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G11-4h_PRJNA612766:
    accessions: [SRR11313421]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G11-10min_PRJNA612766:
    accessions: [SRR11313422]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  F8-4h_PRJNA612766:
    accessions: [SRR11313423]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  F8-10min_PRJNA612766:
    accessions: [SRR11313424]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  F11-4h_PRJNA612766:
    accessions: [SRR11313425]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  F11-10min_PRJNA612766:
    accessions: [SRR11313426]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E6-4h_PRJNA612766:
    accessions: [SRR11313427]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A4-10min_PRJNA612766:
    accessions: [SRR11313428]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E6-10min_PRJNA612766:
    accessions: [SRR11313429]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E3-4h_PRJNA612766:
    accessions: [SRR11313430]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E3-10min_PRJNA612766:
    accessions: [SRR11313431]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E12-4h_PRJNA612766:
    accessions: [SRR11313432]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E12-10min_PRJNA612766:
    accessions: [SRR11313433]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E11-4h_PRJNA612766:
    accessions: [SRR11313434]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  E11-10min_PRJNA612766:
    accessions: [SRR11313435]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D9-4h_PRJNA612766:
    accessions: [SRR11313436]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D9-10min_PRJNA612766:
    accessions: [SRR11313437]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D11-4h_PRJNA612766:
    accessions: [SRR11313438]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A3-4h_PRJNA612766:
    accessions: [SRR11313439]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  D11-10min_PRJNA612766:
    accessions: [SRR11313440]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C9-4h_PRJNA612766:
    accessions: [SRR11313441]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C9-10min_PRJNA612766:
    accessions: [SRR11313442]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C12-4h_PRJNA612766:
    accessions: [SRR11313443]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  C12-10min_PRJNA612766:
    accessions: [SRR11313444]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B9-4h_PRJNA612766:
    accessions: [SRR11313445]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B9-10min_PRJNA612766:
    accessions: [SRR11313446]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B5-4h_PRJNA612766:
    accessions: [SRR11313447]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B3-4h_PRJNA612766:
    accessions: [SRR11313448]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B3-10min_PRJNA612766:
    accessions: [SRR11313449]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A3-10min_PRJNA612766:
    accessions: [SRR11313450]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B2-4h_PRJNA612766:
    accessions: [SRR11313451]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B2-10min_PRJNA612766:
    accessions: [SRR11313452]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B1-4h_PRJNA612766:
    accessions: [SRR11313453]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  B1-10min_PRJNA612766:
    accessions: [SRR11313454]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A11-4h_PRJNA612766:
    accessions: [SRR11313455]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A11-10min_PRJNA612766:
    accessions: [SRR11313456]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A10-4h_PRJNA612766:
    accessions: [SRR11313457]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A10-10min_PRJNA612766:
    accessions: [SRR11313458]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  PC1-4h_PRJNA612766:
    accessions: [SRR11313459]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  PC1-10min_PRJNA612766:
    accessions: [SRR11313460]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A2-4h_PRJNA612766:
    accessions: [SRR11313461]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  NC1-4h_PRJNA612766:
    accessions: [SRR11313462]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  NC1-10min_PRJNA612766:
    accessions: [SRR11313463]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  H9-4h_PRJNA612766:
    accessions: [SRR11313464]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  H9-10min_PRJNA612766:
    accessions: [SRR11313465]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  H12-4h_PRJNA612766:
    accessions: [SRR11313466]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  H12-10min_PRJNA612766:
    accessions: [SRR11313467]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G1-4h_PRJNA612766:
    accessions: [SRR11313468]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  G1-10min_PRJNA612766:
    accessions: [SRR11313469]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  F5-4h_PRJNA612766:
    accessions: [SRR11313470]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  R03-10min_PRJNA612766:
    accessions: [SRR11313471]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  A5-10min_PRJNA612766:
    accessions: [SRR11313472]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A12-4h_PRJNA612766:
    accessions: [SRR11313473]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A12-10min_PRJNA612766:
    accessions: [SRR11313474]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  A6-4h_PRJNA612766:
    accessions: [SRR11313479]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  R16-4h_PRJNA612766:
    accessions: [SRR11313483]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R16-10min_PRJNA612766:
    accessions: [SRR11313484]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R15-4h_PRJNA612766:
    accessions: [SRR11313485]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R15-10min_PRJNA612766:
    accessions: [SRR11313486]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R14-4h_PRJNA612766:
    accessions: [SRR11313487]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R14-10min_PRJNA612766:
    accessions: [SRR11313488]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R13-4h_PRJNA612766:
    accessions: [SRR11313489]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  A6-10min_PRJNA612766:
    accessions: [SRR11313490]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  R13-10min_PRJNA612766:
    accessions: [SRR11313491]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R12-4h_PRJNA612766:
    accessions: [SRR11313492]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R12-10min_PRJNA612766:
    accessions: [SRR11313493]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R11-4h_PRJNA612766:
    accessions: [SRR11313494]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R11-10min_PRJNA612766:
    accessions: [SRR11313495]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R10-4h_PRJNA612766:
    accessions: [SRR11313496]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R10-10min_PRJNA612766:
    accessions: [SRR11313497]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R09-4h_PRJNA612766:
    accessions: [SRR11313498]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R09-10min_PRJNA612766:
    accessions: [SRR11313499]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R08-4h_PRJNA612766:
    accessions: [SRR11313500]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  A5-4h_PRJNA612766:
    accessions: [SRR11313501]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 30-Jan-2020
  R08-10min_PRJNA612766:
    accessions: [SRR11313502]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R07-4h_PRJNA612766:
    accessions: [SRR11313503]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R07-10min_PRJNA612766:
    accessions: [SRR11313504]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R06-4h_PRJNA612766:
    accessions: [SRR11313505]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R06-10min_PRJNA612766:
    accessions: [SRR11313506]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R05-4h_PRJNA612766:
    accessions: [SRR11313507]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R05-10min_PRJNA612766:
    accessions: [SRR11313508]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020
  R04-4h_PRJNA612766:
    accessions: [SRR11313509]
    collected_by: Renmin Hospital of Wuhan University
    collection_date: 12-Feb-2020